import { Metadata, ResolvingMetadata } from "next";

// export const metadata: Metadata = {
//   title: "quiz",
//   description: "Generated by Next.js",
// };

type Props = {
  params: { quizId: string };
  searchParams: { [key: string]: string | string[] | undefined };
};

export function generateMetadata({ params }: Props): Metadata {
  return {
    title: `Quiz n°${params.quizId}`,
    description: `Generated by Next.js. Describe info about quiz ${params.quizId}`,
  };
}

type TypeQuizLayout = {
  children: React.ReactNode;
  params: {
    quizId: string;
  };
};

export default function RootLayout({ children, params }: TypeQuizLayout) {
  return (
    <>
      <nav>
        <h2>This is my navigation</h2>
      </nav>
      {children}
    </>
  );
}
